services:
    # omnisive-server:
    #   container_name: omnisive-server
    #   build:
    #     context: .
    #     dockerfile: Dockerfile
    #   ports:
    #     - '8080:8080'
    #   env_file:
    #     - .env
    #   depends_on:
    #     - postgres
    #     - cassandra
    #     - redis
    #   networks:
    #     - omnisive-network

    postgres:
        container_name: postgres
        image: postgres:15-alpine
        ports:
            - '5432:5432'
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres-data:/var/lib/postgresql/data
        # networks:
        #   - omnisive-network

    cassandra:
        container_name: cassandra
        image: cassandra:latest
        environment:
            CASSANDRA_CLUSTER_NAME: 'omnisive-cluster'
            CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
            CASSANDRA_DC: 'DC1'
            CASSANDRA_RACK: 'RAC1'
        ports:
            - '9042:9042'
        volumes:
            - cassandra-data:/var/lib/cassandra
        # networks:
        #   - omnisive-network

    redis:
        container_name: redis
        environment:
            REDIS_PASSWORD: ${REDIS_PASSWORD}
        image: redis:latest
        ports:
            - '6379:6379'
        # networks:
        #   - omnisive-network

# networks:
#   omnisive-network:
#     driver: bridge

volumes:
    postgres-data:
    cassandra-data:
