global:
  scrape_interval: 4s # How often to scrape targets by default

scrape_configs:
  - job_name: "backend-server"
    static_configs:
      - targets: [
          "backend-server:8080",
        ] # Replace with your service name and port
        labels:
          group: "production"
